"""

Revision ID: 199ad770641d
Revises: 76920bb1628e
Create Date: 2024-07-26 21:21:42.963983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199ad770641d'
down_revision: Union[str, None] = '76920bb1628e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trackCollections_client_association', ['client_id', 'track_collection_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trackCollections_client_association', type_='unique')
    # ### end Alembic commands ###
