"""cascade to client table in profile relationship2

Revision ID: 76920bb1628e
Revises: 3f543ffb825f
Create Date: 2024-07-12 17:32:34.896294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76920bb1628e'
down_revision: Union[str, None] = '3f543ffb825f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_profile_client_id_fkey', 'client_profile', type_='foreignkey')
    op.create_foreign_key(None, 'client_profile', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_profile', type_='foreignkey')
    op.create_foreign_key('client_profile_client_id_fkey', 'client_profile', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
