"""comment in user

Revision ID: c9f8bcaf7c8c
Revises: ce22dc880b8e
Create Date: 2024-02-04 18:08:42.238114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f8bcaf7c8c'
down_revision: Union[str, None] = 'ce22dc880b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
